### ISSUE TITLE
Add Contributors concept

### ISSUE THREAD

**Issue by andymeneely** [kdm2730/CyberStudy#11]
Throughout this website, we need to know who contributed this data so we can trace the source easily. Descriptions can have multiple authors, so this is a many-many situation. For example, the CVE description should link to a "CVE Database" contributor.

**Comment by kdm2730** [comment]
Created a contributor table, need further details on implementation.

**Comment by andymeneely** [comment]
So that we don't make everything be oral tradition, it's probably better to write up those clarifications here.

**Comment by andymeneely** [comment]
You'll want a many-to-many association. Which you can define in the model: http://guides.rubyonrails.org/association_basics.html
