### ISSUE TITLE
View release history for a vulnerability

### ISSUE THREAD

**Issue by andymeneely** [kdm2730/CyberStudy#2]
Show a page with a single vulnerability and show the following pieces of data:
- Date when the vulnerability was introduced
- Date when the vulnerability was fixed
- Releases of the product near those dates

**Comment by andymeneely** [comment]
When I go to https://quiet-beach-9346.herokuapp.com/vuls/1 I get an error.

**Comment by kdm2730** [comment]
Sorry about that Andy! Apparently the database push never happened to
heroku from my local one. The link should work now.

Thanks,
Kyle Murbach

On Wed, Sep 23, 2015 at 9:52 AM, Andy Meneely notifications@github.com
wrote:

> Reopened #2 https://github.com/kdm2730/CyberStudy/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kdm2730/CyberStudy/issues/2#event-416996538.

## 

Kyle Murbach
BS/MS Dual Degree Computing Security 2016
Rochester Institute of Technology

**Comment by kdm2730** [comment]
It may look very basic right now, but I have the database columns set up to
contain the data for the fields that you wanted for that page. I just
wanted to meet with you before going further on that. Also, I have some
questions about the NVD dump as well.

See you at 1.

Thanks,
Kyle Murbach

On Wed, Sep 23, 2015 at 10:34 AM, KYLE MURBACH (RIT Student) <
kdm2730@rit.edu> wrote:

> Sorry about that Andy! Apparently the database push never happened to
> heroku from my local one. The link should work now.
> 
> Thanks,
> Kyle Murbach
> 
> On Wed, Sep 23, 2015 at 9:52 AM, Andy Meneely notifications@github.com
> wrote:
> 
> > Reopened #2 https://github.com/kdm2730/CyberStudy/issues/2.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kdm2730/CyberStudy/issues/2#event-416996538.
> 
> ## 
> 
> Kyle Murbach
> BS/MS Dual Degree Computing Security 2016
> Rochester Institute of Technology

## 

Kyle Murbach
BS/MS Dual Degree Computing Security 2016
Rochester Institute of Technology
