### ISSUE TITLE
Draw a timeline of dates visually on the vulnerability detail page

### ISSUE THREAD

**Issue by andymeneely** [kdm2730/CyberStudy#6]
Pages sort of like this might be cool: 

http://codyhouse.co/demo/vertical-timeline/index.html

**Comment by andymeneely** [comment]
Note: as of b0371f0ce0741096f619c3332f01579b9bff65bb we're tabling this until we can figure out a better way to do it.

**Comment by andymeneely** [comment]
Here's one that uses only bootstrap: http://codepen.io/betdream/pen/Ifvbi/

**Comment by kdm2730** [comment]
Implemented and pushed onto heroku. Visit any of the vulnerabilities in the vulnerability tab to view a semi-comprehensive timeline of that vulnerability.  Further details need to be hashed out for it to be fully functional with dates etc.
